title: <p align="center"> Surya Chandra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/suryachandu9">GitHub</a>
  
  <br>   
      I'm a student at UpGrad. Masters in ML & AI
  <br>
  </p>



theme: jekyll-theme-minimal

